<?php
/**
 * @file
 * Hooks and other module requirements.
 */

// Use the class 4 autoloder to load classes as they are called.
require_once 'vendor/autoload.php';

/**
 * Implements hook_help().
 */
function hook_update_deploy_tools_help($path, $arg) {
  switch ($path) {
    case 'admin/help#hook_update_deploy_tools':
      $output = file_get_contents(drupal_get_path('module', 'hook_update_deploy_tools') . '/README.md');
      if (module_exists('markdown')) {
        // Markdown can be used.
        module_load_include('php', 'markdown', 'markdown');
        $output = Markdown($output);
      }
      else {
        // Markdown is not available.
        $output = '<pre>' . $output . '</pre>';
      }
      return $output;
  }
}

/**
 * Implements hook_menu().
 */
function hook_update_deploy_tools_menu() {
  $items['admin/config/development/hook_update_deploy_tools'] = array(
    'title' => 'Hook Update Deploy Tools Settings',
    'description' => 'Settings for the Hook Update Deploy Tools module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('hook_update_deploy_tools_admin'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * The callback function creates an admin form for a menu hook.
 */
function hook_update_deploy_tools_admin() {
  $form = array();

  $default_deploy = check_plain(variable_get('hook_update_deploy_tools_deploy_module', ''));
  $description = t("This is the machine name for the custom deploy module for the site. example: site_deploy");
  if (empty($default_deploy)) {
    $vars = array('%drush' => 'drush site-deploy-init');
    $description .= '</br>' . t("You currently have no deploy module declared.  Run '%drush' to create one.", $vars);
  }
  $form['hook_update_deploy_tools_deploy_module'] = array(
    '#type' => 'textfield',
    '#title' => t('Machine name of the custom deploy module for this site.'),
    '#default_value' => $default_deploy,
    '#size' => 60,
    '#maxlength' => 60,
    '#description' => $description,
    '#required' => FALSE,
  );

  $description = t("This is the machine name for the Feature controlling the menus. example: my_menu_feature.") . '</br>';
  $description .= t("This determines where Menu import files must reside.") . '</br>';
  $path = HookUpdateDeployTools\HudtInternal::getStoragePath('menu', TRUE);
  $description .= t("Currently using: %path", array('%path' => $path));
  $form['hook_update_deploy_tools_menu_feature'] = array(
    '#type' => 'textfield',
    '#title' => t('Machine name of menu Feature or custom deploy module'),
    '#default_value' => check_plain(variable_get('hook_update_deploy_tools_menu_feature', '')),
    '#size' => 60,
    '#maxlength' => 60,
    '#description' => $description,
    '#required' => FALSE,
  );

  $description = t("This is the machine name for the Feature controlling the Rules. example: my_rules_feature.") . '</br>';
  $description .= t("This determines where Rules import files must reside.") . '</br>';
  $path = HookUpdateDeployTools\HudtInternal::getStoragePath('rules', TRUE);
  $description .= t("Currently using: %path", array('%path' => $path));
  $form['hook_update_deploy_tools_rules_feature'] = array(
    '#type' => 'textfield',
    '#title' => t('Machine name of Rule Feature or custom deploy module'),
    '#default_value' => check_plain(variable_get('hook_update_deploy_tools_rule_feature', '')),
    '#size' => 60,
    '#maxlength' => 60,
    '#description' => $description,
    '#required' => FALSE,
  );

  return system_settings_form($form);
}
